
-- Dipinsa Marasini
-- Restaurant Order Management Database
-- Oracle SQL | Database Management Systems | UT Arlington

-- drop
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDER_DETAIL CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE ORDERS CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE MENU_ITEM CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE EMPLOYEE CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/
BEGIN EXECUTE IMMEDIATE 'DROP TABLE CUSTOMER CASCADE CONSTRAINTS'; EXCEPTION WHEN OTHERS THEN NULL; END;
/

-- PART A: CREATE TABLES

-- 1) CUSTOMER

CREATE TABLE CUSTOMER (
  CustomerID  NUMBER(6) PRIMARY KEY,
  FirstName   VARCHAR2(30),
  LastName    VARCHAR2(30),
  Phone       VARCHAR2(20),
  Email       VARCHAR2(60)
);

-- 2) MENU_ITEM

CREATE TABLE EMPLOYEE (
  EmployeeID  NUMBER(6) PRIMARY KEY,
  EmpName     VARCHAR2(50),
  Role        VARCHAR2(30),
  Salary      NUMBER(10,2)
);

-- 3) EMPLOYEE

CREATE TABLE MENU_ITEM (
  ItemID    NUMBER(6) PRIMARY KEY,
  ItemName  VARCHAR2(60),
  Category  VARCHAR2(30),
  Price     NUMBER(8,2)
);


-- 4) ORDERS

CREATE TABLE ORDERS (
  OrderID     NUMBER(8) PRIMARY KEY,
  CustomerID  NUMBER(6),
  EmployeeID  NUMBER(6),
  OrderDate   DATE,
  TotalAmount NUMBER(10,2),
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
  FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID)
);


-- 5) ORDER_DETAIL (line items for an order)

CREATE TABLE ORDER_DETAIL (
  OrderID   NUMBER(8),
  ItemID    NUMBER(6),
  Quantity  NUMBER(6),
  PRIMARY KEY (OrderID, ItemID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
  FOREIGN KEY (ItemID)  REFERENCES MENU_ITEM(ItemID)
);


-- INSERT DATA (3 rows per table, different dataset)


INSERT INTO CUSTOMER VALUES (201,'Noah','Bennett','682-555-1111','noah.b@example.com');
INSERT INTO CUSTOMER VALUES (202,'Lina','Rojas','682-555-2222','lina.r@example.com');
INSERT INTO CUSTOMER VALUES (203,'Dev','Patel','682-555-3333','dev.p@example.com');

INSERT INTO EMPLOYEE VALUES (601,'Mason Reed','Waiter',31000);
INSERT INTO EMPLOYEE VALUES (602,'Zara Khan','Server',37200);
INSERT INTO EMPLOYEE VALUES (603,'Victor Lin','Manager',54000);

INSERT INTO MENU_ITEM VALUES (301,'Veg Korma','Main',12.50);
INSERT INTO MENU_ITEM VALUES (302,'Chicken Biryani','Main',14.25);
INSERT INTO MENU_ITEM VALUES (303,'Garlic Naan','Bread',3.25);
INSERT INTO MENU_ITEM VALUES (304,'Samosa (2pc)','Starter',5.50);
INSERT INTO MENU_ITEM VALUES (305,'Rose Falooda','Drink',6.75);

INSERT INTO ORDERS VALUES (9101,201,601,TO_DATE('2025-10-15','YYYY-MM-DD'), (14.25 + 3.25));
INSERT INTO ORDERS VALUES (9102,202,602,TO_DATE('2025-10-16','YYYY-MM-DD'), (12.50 + 5.50 + 6.75));
INSERT INTO ORDERS VALUES (9103,203,602,TO_DATE('2025-10-17','YYYY-MM-DD'), (12.50 + 3.25));

INSERT INTO ORDER_DETAIL VALUES (9101,302,1);
INSERT INTO ORDER_DETAIL VALUES (9101,303,1);

INSERT INTO ORDER_DETAIL VALUES (9102,301,1);
INSERT INTO ORDER_DETAIL VALUES (9102,304,1);
INSERT INTO ORDER_DETAIL VALUES (9102,305,1);

INSERT INTO ORDER_DETAIL VALUES (9103,301,1);
INSERT INTO ORDER_DETAIL VALUES (9103,303,1);

COMMIT;



-- PART B: QUERIES


-- 1
SELECT ItemName, Price FROM MENU_ITEM WHERE Price > 10;

-- 2
SELECT c.FirstName || ' ' || c.LastName AS FullName, o.OrderID, o.TotalAmount
FROM CUSTOMER c
JOIN ORDERS o ON o.CustomerID = c.CustomerID
ORDER BY o.TotalAmount DESC;

-- 3
SELECT o.OrderID, e.EmpName, e.Role
FROM ORDERS o
JOIN EMPLOYEE e ON e.EmployeeID = o.EmployeeID;

-- 4
SELECT DISTINCT c.FirstName || ' ' || c.LastName AS CustomerName
FROM CUSTOMER c
JOIN ORDERS o ON o.CustomerID = c.CustomerID
JOIN ORDER_DETAIL od ON od.OrderID = o.OrderID
JOIN MENU_ITEM m ON m.ItemID = od.ItemID
WHERE m.ItemName = 'Chicken Biryani';

-- 5
SELECT Role, AVG(Salary) AS AvgSalary
FROM EMPLOYEE
GROUP BY Role;
